'use client'
import { useEffect, useRef, useState } from 'react'
import { Command, Menu, Moon, Printer, Search, Shield, Sun, X } from 'lucide-react'
import { useTheme } from './ThemeProvider'

export default function Navbar({ onSearch, onPrint, onMenuOpen }) {
  const { theme, toggle } = useTheme()
  const [query, setQuery] = useState('')
  const [scrolled, setScrolled] = useState(false)
  const inputRef = useRef(null)
  useEffect(() => { const handler = () => setScrolled(window.scrollY > 12); window.addEventListener('scroll', handler, { passive: true }); return () => window.removeEventListener('scroll', handler) }, [])
  const change = event => { setQuery(event.target.value); onSearch(event.target.value) }
  const clear = () => { setQuery(''); onSearch(''); inputRef.current?.focus() }

  return <nav className={`fixed inset-x-0 top-0 z-50 no-print transition-all ${scrolled ? 'border-b border-slate-200/70 bg-white/90 shadow-[0_8px_30px_rgba(15,23,42,.08)] backdrop-blur-xl dark:border-white/10 dark:bg-[#07111f]/90' : 'bg-transparent'}`}><div className="mx-auto flex h-[72px] max-w-[1440px] items-center gap-3 px-4 sm:px-6"><button onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })} className="flex flex-none items-center gap-3 text-left"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#e32636] text-white shadow-lg shadow-red-500/20"><span className="text-xl font-black">+</span></span><span className="hidden sm:block"><b className="block text-sm font-black tracking-tight text-slate-950 dark:text-white">BEACH TOWN EMS</b><span className="mt-0.5 flex items-center gap-1.5 text-[9px] font-bold uppercase tracking-[.18em] text-slate-500 dark:text-slate-400"><i className="h-1.5 w-1.5 rounded-full bg-emerald-500" />Protocol Center</span></span></button><div className="mx-auto flex-1 sm:max-w-lg"><label className="group relative block"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input ref={inputRef} value={query} onChange={change} placeholder="Tìm quy định, tình huống…" className="h-10 w-full rounded-2xl border border-slate-200 bg-white/80 pl-10 pr-10 text-sm text-slate-900 shadow-sm outline-none transition focus:border-red-400 focus:ring-4 focus:ring-red-500/10 dark:border-white/10 dark:bg-white/5 dark:text-white" />{query && <button onClick={clear} className="absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-1 text-slate-400 hover:bg-slate-100 dark:hover:bg-white/10" aria-label="Xóa tìm kiếm"><X className="h-3.5 w-3.5" /></button>}</label></div><div className="flex flex-none items-center gap-1.5"><button onClick={onPrint} className="hidden h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-xs font-bold text-slate-700 shadow-sm hover:border-slate-300 md:flex dark:border-white/10 dark:bg-white/5 dark:text-white"><Printer className="h-4 w-4" /> Xuất PDF</button><a href="/admin" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 bg-white text-slate-600 shadow-sm hover:text-red-600 dark:border-white/10 dark:bg-white/5 dark:text-white" title="Quản trị"><Shield className="h-4 w-4" /></a><button onClick={toggle} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 bg-white text-slate-600 shadow-sm dark:border-white/10 dark:bg-white/5 dark:text-white" aria-label="Đổi giao diện">{theme === 'dark' ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}</button><button onClick={onMenuOpen} className="grid h-10 w-10 place-items-center rounded-xl bg-slate-950 text-white lg:hidden dark:bg-white dark:text-slate-950" aria-label="Mở mục lục"><Menu className="h-4 w-4" /></button></div></div></nav>
}
